const RESET_BOOKING = 'RESET_BOOKING';
const SET_BOOKING_USER = 'SET_BOOKING_USER';
const SET_BOOKING_HOUSE = 'SET_BOOKING_HOUSE';
const SET_BOOKING_ARRIVAL = 'SET_BOOKING_ARRIVAL';
const SET_BOOKING_DEPARTURE = 'SET_BOOKING_DEPARTURE';
const SET_BOOKING_TRAVELLERS_NUMBERS = 'SET_BOOKING_TRAVELLERS_NUMBERS';
const UPDATE_BOOKING_OPTION = 'UPDATE_BOOKING_OPTION';

export {
  RESET_BOOKING,
  SET_BOOKING_USER,
  SET_BOOKING_HOUSE,
  SET_BOOKING_ARRIVAL,
  SET_BOOKING_DEPARTURE,
  SET_BOOKING_TRAVELLERS_NUMBERS,
  UPDATE_BOOKING_OPTION,
};
